// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPDIivO_ee2iQJPiN4rgmu7PqwPD_A4w',
    appId: '1:959825401473:web:2f64025648cd0e4fd59f80',
    messagingSenderId: '959825401473',
    projectId: 'mindjar-86510',
    authDomain: 'mindjar-86510.firebaseapp.com',
    storageBucket: 'mindjar-86510.appspot.com',
    measurementId: 'G-Y3P05SG2W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZR1701WYF3xeCs8GmoeQX-cEV-2cRn0',
    appId: '1:959825401473:android:d4177c1c8e87dc0cd59f80',
    messagingSenderId: '959825401473',
    projectId: 'mindjar-86510',
    storageBucket: 'mindjar-86510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvZZwRQbbZjqlofReAY-ijVcjt-S4N3R4',
    appId: '1:959825401473:ios:5b6b93dd127dad93d59f80',
    messagingSenderId: '959825401473',
    projectId: 'mindjar-86510',
    storageBucket: 'mindjar-86510.appspot.com',
    iosBundleId: 'com.example.mindjar',
  );
}
